/* Victorian Manchester natural-history workbook, restructured as a graph.
   Every node and edge below is asserted somewhere in the workbook; nothing is
   invented. `ev` records how firmly the workbook itself states the link. */

const DOMAINS = {
  nat:    { label: "Natural history",      css: "--d-nat" },
  press:  { label: "Press & publishing",   css: "--d-press" },
  trade:  { label: "Industry & commerce",  css: "--d-trade" },
  suff:   { label: "Women's rights",       css: "--d-suff" },
  reform: { label: "Reform & abolition",   css: "--d-reform" },
  civic:  { label: "Civic & institutions", css: "--d-civic" },
  arts:   { label: "Arts & performance",   css: "--d-arts" }
};

const EVIDENCE = {
  documented:  { label: "Stated in workbook", dash: null,    note: "Asserted directly by a workbook row." },
  verify:      { label: "Needs verification", dash: "5 3",   note: "Flagged in the workbook as unconfirmed." },
  interpretive:{ label: "Interpretive",       dash: "1.5 3", note: "A hypothesis the workbook offers for testing." }
};

const TYPES = {
  person: { label: "People" },
  org:    { label: "Societies & firms" },
  place:  { label: "Places" }
};

/* [id, name, type, domain, dates, role, note, sheetId, flag] */
const RAW_NODES = [
  // ---------- natural history: the artisan botanists ----------
  ["buxton","Richard Buxton","person","nat","1786–1865","Botanist & shoemaker","Self-taught; wrote an 1849 guide to plants within sixteen miles of Manchester. Working-class autodidact.","NH-001"],
  ["horsefield","John Horsefield","person","nat","1792–1854","Botanist & handloom weaver","Founded the Prestwich Botanical Society in 1820 and led the regional networks for over thirty years.","NH-002"],
  ["hobson","Edward Hobson","person","nat","1782–1830","Bryologist & artisan naturalist","Early Manchester specialist in mosses and liverworts; prepared Musci Britannici material.","NH-003"],
  ["jsidebotham","Joseph Sidebotham","person","nat","1824–1885","Cotton industrialist & naturalist","Botany, entomology, microscopy and photography. Collections entered Manchester Museum.","NH-004"],
  ["jlphilips","John Leigh Philips","person","nat","1761–1814","Textile manufacturer & collector","His private collection became foundational to Manchester's museum institutions.","NH-005","Date conflict: a University page gives 1761–1841; the Museum archive gives 1761–1814."],
  ["cribb","Robert Cribb","person","nat","dates unknown","Textile worker & lepidopterist","Credited with finding the Manchester moth at Kersal Moor in 1829. Credit later disputed.","NH-006"],
  ["rwood","R. Wood","person","nat","dates unknown","Insect collector","The Manchester moth was named for Wood rather than Cribb. Relationship to Cribb needs careful sourcing.","NH-007"],
  ["carrington","Benjamin Carrington","person","nat","1827–1893","Physician & botanist","Bryophytes, cryptogams, fungi and lichens. Author of Hepaticae Britannicae exsiccatae.","NH-008"],
  ["bailey","Charles Bailey","person","nat","1838–1924","Botanist & collector","Built one of the three major personal herbaria absorbed by Manchester Museum, in 1917.","NH-009"],
  ["melvill","Cosmo Melvill","person","nat","1845–1929","Naturalist & collector","Botany and conchology. His general herbarium entered the Museum in 1904.","NH-010"],
  ["sgibson","Samuel Gibson","person","nat","dates unknown","Artisan botanist & collector","Ferns, algae and other cryptogams represented in Manchester's herbarium.","NH-011"],
  ["nowell","John Nowell","person","nat","dates unknown","Bryologist","Collaborated with Buxton on a fasciculus of British mosses.","NH-012"],
  ["crozier","George Crozier","person","nat","dates unknown","Artisan naturalist","Remembered by Grindon as practising natural history alongside manual work in a Shudehill workshop.","NH-013"],
  ["crowther","John Crowther","person","nat","1768–unknown","Artisan botanist","An early participant in the rotating Lancashire botanical meetings; described by Grindon as a 'Banksian'.","NH-014"],
  ["thsidebotham","Thomas Henry Sidebotham","person","nat","dates unknown","Naturalist","Potential member of the wider Sidebotham scientific network. Identity needs confirming.","NH-015"],
  ["crowe","John Crowe","person","nat","19th century","Botanist","Named by Grindon among Manchester botanists attending regional gatherings.","NH-016"],
  ["warburton","John Warburton","person","nat","19th century","Botanist","Named by Grindon among Manchester botanists attending regional gatherings.","NH-017"],
  ["hulme","George Hulme","person","nat","19th century","Botanist","Named by Grindon among Prestwich botanists attending regional gatherings.","NH-018"],
  ["eclough","Edwin Clough","person","nat","19th century","Botanist","Named by Grindon among Ashton-under-Lyne botanists at regional gatherings.","NH-019"],
  ["hnewton","Henry Newton","person","nat","19th century","Botanist","Ashton-under-Lyne. Which Newton this is remains to be confirmed.","NH-020"],
  ["bleackley","Tom Bleackley","person","nat","19th century","Botanist","Whitefield; named by Grindon among local botanists at regional gatherings.","NH-021"],
  ["jshaw","John Shaw","person","nat","19th century","Botanist","Eccles; named by Grindon among local botanists at regional gatherings.","NH-022"],
  ["darbyshire","John Darbyshire","person","nat","19th century","Botanist","Newton; named by Grindon among local botanists at regional gatherings.","NH-023"],
  ["bentley","William Bentley","person","nat","19th century","Botanist","Royton; spelling and full identity need verifying.","NH-024"],
  ["devonport","James Devonport","person","nat","19th century","Botanist","Droylsden; named by Grindon among local botanists at regional gatherings.","NH-025"],
  ["jturner","John Turner","person","nat","19th century","Botanist","Middleton. Needs disambiguating from other John Turners.","NH-026"],
  ["hopkins","Mrs Hopkins","person","nat","1879–1881 active","Plant collector","Herbarium sheets survive under this name alone. Full name, biography and collecting locations lost.","NH-027","Recorded only as 'Mrs Hopkins'. Recovering her own name is an open workshop task."],
  ["jaffrey","Mrs P. Jaffrey","person","nat","1882 active","Fern collector","Darjeeling ferns documented in Manchester's herbarium guide. A colonial collecting route with the intermediaries unnamed.","NH-028","Recorded only as 'Mrs P. Jaffrey'. The collector and her intermediaries are unidentified."],
  ["grindon","Leo H. Grindon","person","nat","1818–1904","Cashier, self-taught naturalist & adult educator","Founded the Manchester Field-Naturalists' Society; wrote Manchester Flora (1859) and Country Rambles (1882). Lectured in botany at the Royal School of Medicine from 1852.","sw","ID recorded as 'sw' and flagged DUPLICATE ID in the workbook."],
  ["rgrindon","Rosa Leo Grindon","person","suff","1820–1900","Lecturer","Wrote 'Shakespeare plays from a women's point of view'. Connector between natural history and women's literary organisation.","200069"],
  ["wcwilliamson","William Crawford Williamson","person","nat","dates missing","Curator & professor","First curator of the Peter Street museum, 1835, and Professor of Natural History at Owens College.","—","No ID, no dates, no source in the workbook."],
  ["curtis","John Curtis","person","nat","external","Taxonomist","Described and named the Manchester moth, apparently from a specimen attributed to Wood.","—","Appears only inside relationship text; has no People row."],
  ["pearson","William Henry Pearson","person","nat","external","Botanist","Named in Carrington's herbarium network.","—","Appears only inside relationship text; has no People row."],
  ["brittain","Thomas Brittain","person","nat","external","Microscopist","Named among the founders of the first Manchester Microscopical Society, 1858.","—","Appears only in the Organisations sheet; has no People row."],
  ["cash","James Cash","person","nat","external","Cryptogamist","Named in the Manchester Cryptogamic Society entry.","—","Appears only in the Organisations sheet; has no People row."],

  // ---------- press: the Guardian and the Little Circle ----------
  ["jetaylor","John Edward Taylor","person","press","1791–1844","Founder & editor","Founded the Manchester Guardian. Liberal, Unitarian, active 1820s–1840s.","200100","Duplicated in the workbook as 200013 with the same dates."],
  ["jetaylor2","John Edward Taylor II","person","press","1830–1905","Editor & owner","Son of John Edward Taylor; co-owner in 1852, sole owner in 1856.","200111"],
  ["cowdroy","William Cowdroy Jr.","person","press","1775–1831","Editor, Manchester Gazette","Member of the Little Circle; contributed to the founding of the Manchester Guardian.","200106"],
  ["prentice","Archibald Prentice","person","press","1792–1857","Editor, Manchester Times","Member of the Little Circle; radical; financial backer of the Manchester Guardian.","200108"],
  ["rscott","Russell Scott","person","press","1801–1880","Coal merchant & philanthropist","Brother-in-law to John Edward Taylor; invested in the Guardian and became proprietor after Taylor's death.","200110"],
  ["sophiataylor","Sophia Russell Taylor","person","arts","1793–1866","Cultural hostess","Wife of John Edward Taylor; hosted cultural salons in Manchester.","200097"],

  // ---------- industry & commerce ----------
  ["gphilips","Sir George Philips","person","trade","1766–1847","Financier & MP","West India merchant and enslaver; partner in Boddington, Sharp and Philips, which owned the Success estate in Hanover, Jamaica. The Guardian backer most deeply linked with slavery.","200101"],
  ["tpotter","Thomas Potter","person","trade","1774–1845","First Mayor of Manchester","Member of the Little Circle. Mayor 1838–40. Connected to transatlantic slavery through the cotton and textile trade.","200104","Also appears garbled as 200016, 'Thom & Richard Potter'."],
  ["rpotter","Richard Potter","person","trade","1778–1842","MP for Wigan","'Radical Dick'. Little Circle member; manufacturer and dealer in cotton goods; owned a Manchester textile warehouse.","200105"],
  ["jpotter","John Potter","person","trade","1773–1838","Merchant","Host of the Little Circle meetings; father to Thomas and Richard Potter.","200109"],
  ["shuttleworth","John Shuttleworth","person","trade","1786–1864","Industrialist & reformer","Co-founded Shuttleworth, Taylor & Co., which imported cotton produced by enslaved people from the Sea Islands.","200102","Duplicated as 200014 with the same dates."],
  ["gwwood","George William Wood","person","trade","dates missing","Merchant & MP","Partner in Philips, Wood & Co and Shuttleworth, Taylor & Co. Twice president of the Chamber of Commerce.","—","No ID and no dates in the workbook."],
  ["rphilips","Robert Philips","person","trade","dates missing","Merchant","Cousin of Sir George Philips; partnerships in Philips, Wood & Co and Shuttleworth, Taylor & Co; family ties to the Hibbert and Yates enslaver families.","—","No ID and no dates in the workbook."],
  ["baxter","Edward Baxter","person","trade","dates missing","Cotton merchant","Unitarian calico printer and muslin manufacturer; founder-director of the Manchester Savings Bank.","—","No ID and no dates in the workbook."],
  ["duckworth","William Duckworth","person","trade","dates missing","Attorney","Unitarian; son-in-law of Robert Philips. Recorded in 1826 supporting the melioration of the enslaved population of the colonies.","—","No ID and no dates in the workbook."],
  ["pullein","Samuel Pullein","person","trade","dates missing","Calico printer","Director and trustee of the Manchester Fire and Life Assurance Company.","—","No ID and no dates in the workbook."],
  ["sanderson","Thomas BW Sanderson","person","trade","dates missing","Merchant & manufacturer","Dealer in cotton goods and supplies; linked to transatlantic slavery through his business operations.","—","No ID and no dates in the workbook."],
  ["tjohnson","Thomas Johnson","person","trade","dates missing","Merchant","Named as a merchant in the original Manchester Guardian loan agreement.","—","No ID and no dates in the workbook."],
  ["twilkins","Thomas Wilkins","person","trade","dates missing","Merchant","Named in the Guardian loan agreement; a secondary source lists him as a cotton merchant.","—","No ID and no dates in the workbook."],
  ["whitworth","Joseph Whitworth","person","trade","1803–1887","Inventor","Engineer and machine-tool maker; commemorated by statues at the Royal Infirmary.","200023"],
  ["mlwhitworth","Mary Louisa Whitworth","person","trade","1823–1896","Philanthropist","Second wife of Joseph Whitworth; inherited and continued his charitable work.","200096"],
  ["rylands","John Rylands","person","trade","1801–1888","Merchant","Married three times; the last to Enriqueta Tennant, eight months after Martha's death.","200024"],
  ["erylands","Enriqueta Augustina Rylands","person","trade","1843–1908","Founder & patron","Founded the John Rylands Library in memory of her husband; a major patron of education.","200040"],
  ["adamson","Daniel Adamson","person","trade","1820–1890","Ship Canal engineer","Drove the Manchester Ship Canal, opened 1894.","200019"],
  ["murray","Murray brothers","person","trade","various","Factory owners, Ancoats","Mill owners on Oxford Road and the River Medlock.","200048"],
  ["mcconnel","McConnel","person","trade","various","Factory owners, Ancoats","Mill owners on Oxford Road and the River Medlock.","200049"],
  ["kennedy","Kennedy","person","trade","various","Factory owners, Ancoats","Mill owners on Oxford Road and the River Medlock.","200050"],
  ["swatts","S&J Watts","person","trade","various","Warehousemen","Their warehouse is now the Britannia Hotel.","200058"],
  ["wfairbairn","William Fairbairn","person","trade","1789–1874","Engineer","Commemorated by statues at the Royal Infirmary.","200059","Spelled 'Fairburn' in the workbook."],
  ["tfairbairn","Thomas Fairbairn","person","trade","1823–91","Industrialist & art patron","Commissioner at the Great Exhibition 1851; headed the executive committee of the Art Treasures Exhibition 1857.","sw","ID recorded as 'sw'."],
  ["bazley","Thomas Bazley","person","trade","1797–1885","MP","Charitable work, status and local power.","200030"],
  ["jaturner","JA Turner","person","trade","dates unknown","MP","'You need to be local and charitable to get on.' Palmerstonian.","200018","Descriptive note is embedded in the Name field."],
  ["callender","William Romaine Callender jnr","person","trade","1825–1876","Merchant","Palmerstonian/conservative.","200029"],
  ["holdsworth","William Henry Holdsworth","person","trade","dates unknown","—","Charitable work, status and local power.","200031"],
  ["forwood","Arthur Brown Forwood","person","trade","1836–1898","Liverpool merchant","Pro-slavery supporter.","200009","Descriptive note is embedded in the Name field."],
  ["dresser","Henry Dresser","person","trade","1838–1915","Merchant","London-based; broke the cotton embargo.","200010","Name field ends mid-sentence: 'backed by'."],
  ["sichel","Julius Sichel","person","trade","1802–1868","Austrian vice-consul","Manchester Museum holds his diaries.","200011","Descriptive note is embedded in the Name field."],
  ["mosley","Mosley family","person","trade","various","Lords of the manor","Sold the rights of lord of the manor of Manchester to Manchester Corporation in 1846.","200046","Spelled 'Mosley familu'."],
  ["jwilliamson","James Williamson","person","trade","1842–1930","MP","Involved in the Manchester Royal Jubilee Exhibition.","200025"],
  ["markphillips","Mark Phillips","person","trade","1800–1873","MP","—","200033"],
  ["sirjohnpotter","Sir John Potter","person","trade","1815–1858","—","Charitable work, status and local power.","200017"],
  ["jgroves","James Groves","person","trade","dates unknown","Founder","Salford Lads Club; Groves and Whitnall Breweries.","200041"],
  ["wgroves","William Groves","person","trade","dates unknown","Founder","Salford Lads Club; Groves and Whitnall Breweries.","200042"],
  ["beardsley","William & Joseph Beardsley","person","trade","19th century","Garden proprietors","Opened Strawberry Gardens, later Pomona Gardens, in 1845.","sw","ID recorded as 'sw'."],
  ["heywood","Benjamin Heywood","person","trade","1793–1865","MP & philanthropist","Charitable work, status and local power.","200020","Role recorded as 'MP, Philanthropost'."],
  ["greg","Greg family","person","trade","various","Campaigners","Anti-slavery.","200002"],
  ["lees","Lees family","person","trade","various","Campaigners","Anti-slavery.","200003"],

  // ---------- women's rights & suffrage ----------
  ["becker","Lydia Becker","person","suff","1827–1890","Scientist & suffragist","Won a gold medal in the 1864 botanical competition; founded the Manchester suffrage society and edited the Women's Suffrage Journal. Self-taught scientist, suffrage organiser, editor.","200068"],
  ["roper","Esther Roper","person","suff","1868–1938","Suffragist","Secretary of the Manchester National Society for Women's Suffrage from 1893; recruited working-class women into the movement.","200084"],
  ["gorebooth","Eva Gore-Booth","person","suff","1870–1926","Poet & suffragist","Partner of Esther Roper; campaigned for women's and workers' rights. Labour, spiritualist, 1890s–1910s.","200085"],
  ["pankhurst","Emmeline Pankhurst","person","suff","1858–1928","Suffragette","Elected Poor Law Guardian for Chorlton-on-Medlock in 1894.","200021"],
  ["kenney","Annie Kenney","person","suff","1879–1953","Suffragette","The only working-class woman in a senior leadership position in the WSPU.","200079"],
  ["mitchell","Hannah Mitchell","person","suff","1872–1956","Socialist & suffragette","Involved in the fights for women's suffrage and pacifism.","200076"],
  ["ashton","Margaret Ashton","person","suff","1856–1937","Politician","First woman city councillor for Manchester, 1908. Pacifist; split from the suffragette movement before the war.","200077"],
  ["maxwell","Lily Maxwell","person","suff","c.1800–1876","Suffragist","One of the first women to vote, illegally. Connected to the Chorlton v Lings case.","200062"],
  ["quaile","Mary Quaile","person","suff","1886–1958","Trade unionist","Secretary of the Manchester Women's Trade Union Council. Born in Dublin, grew up in Manchester.","200078","Spelled 'Mary Qualie'; the linked source spells it Quaile."],
  ["martyn","Caroline Martyn","person","suff","1867–1896","Socialist speaker","Worked alongside the Labour leader Keir Hardie. ILP and trade unions.","200086"],
  ["ubright","Ursula Mellor Bright","person","suff","1835–1915","Suffragist & activist","Wife of Jacob Bright; campaigner for women's legal and voting rights.","200099"],
  ["mbright","Margaret Elizabeth Bright","person","suff","1818–1890","Philanthropist","Second wife of John Bright; active in women's education.","200094","Workbook calls her 'sister to Jacob Bright' — likely sister-in-law. Worth resolving."],
  ["fildes","Mary Fildes","person","suff","c.1789–1876","Reformer","Irish-born president of the Manchester Female Reform Society; led the female reformers' contingent at Peterloo.","200001"],
  ["stopes","Marie Stopes","person","suff","1880–1958","Birth control campaigner","—","200039","Active well after the Victorian period; the People sheet has no scope flag."],
  ["remond","Sarah Parker Remond","person","reform","1826–1894","Abolitionist & physician","African-American abolitionist who campaigned in Manchester and delivered speeches at the Athenaeum.","200066"],
  // referenced in events but absent from People
  ["wolstenholme","Elizabeth Wolstenholme-Elmy","person","suff","—","Suffragist","Present at the formation of the Manchester Society for Women's Suffrage, 1867, and founder of the Schoolmistresses Association, 1865.","—","Named in the events sheet; has no People record."],
  ["rpankhurst","Richard Pankhurst","person","suff","—","Barrister","Present at the formation of the Manchester Society for Women's Suffrage, 1867.","—","Named in the events sheet; has no People record."],
  ["dickenson","Sarah Dickenson","person","suff","—","Trade unionist","Co-formed the Manchester and Salford Women's Trades Council, 1895.","—","Named in the events sheet; has no People record."],
  ["pochin","Agnes Pochin","person","suff","—","Suffrage speaker","Spoke at the first public meeting at the Free Trade Hall, 1868; her husband, then Mayor of Salford, chaired it.","—","Named in the events sheet; has no People record."],
  ["brightmclaren","Priscilla Bright McLaren","person","suff","—","Suffragist","Spoke at the first public meeting of the Manchester National Society, 1868.","—","Named in the events sheet; has no People record."],
  ["butler","Josephine Butler","person","suff","—","Campaigner","Joined the society's new executive committee in October 1868.","—","Named in the events sheet; has no People record."],
  ["davies","Emily Davies","person","suff","—","Education campaigner","Addressed the Manchester Schoolmistresses Board on women's higher education, October 1866.","—","Named in the events sheet; has no People record."],
  ["aclough","Anne Clough","person","suff","—","Educationist","Honorary member of the Manchester Schoolmistresses Association, 1865.","—","Named in the events sheet; has no People record."],
  ["robertson","Anne Robertson","person","suff","—","Suffrage speaker","Spoke at the first public meeting of the society, 1868.","—","Named in the events sheet; has no People record."],

  // ---------- reform & abolition ----------
  ["sharp","Granville Sharp","person","reform","1735–1813","Campaigner","Anti-slavery, with Wilberforce in London. Died unmarried in 1813.","200005","Descriptive note is embedded in the Name field."],
  ["clarkson","Thomas Clarkson","person","reform","1760–1846","Campaigner","Quaker abolitionist. Married in 1796; their only child, Thomas, died before his father. Westminster Abbey.","200006"],
  ["cclarkson","Catherine Buck Clarkson","person","reform","dates not known","Supporter","Supported her husband's abolitionist work and managed home life during the campaigns.","200092"],
  ["jbright","John Bright","person","reform","1811–1889","Campaigner","Free Trade and Liberal. Married Elizabeth Priestman in 1839; she died in 1841. Remarried Margaret Elizabeth Leatham in 1847.","200012"],
  ["jacobbright","Jacob Bright","person","reform","1821–1899","—","Husband of Ursula Mellor Bright.","200032"],
  ["cobden","Richard Cobden","person","reform","1804–1865","Supporter & MP","Anti-slavery and Free Trade. Married in 1840; five surviving children. Westminster Abbey.","200008"],
  ["ccobden","Catherine Anne Cobden","person","reform","1815–1877","Campaigner","Supported education and published her husband's letters posthumously.","200091","Cobden's own row calls her 'Catherine Anne Williams'; her row calls her Cobden."],
  ["engels","Friedrich Engels","person","reform","1820–1895","Socialist","Had long-term relationships with Mary Burns and later her sister Lydia, but did not marry.","200035"],
  ["marx","Karl Marx","person","reform","1818–1883","Socialist","Childhood sweetheart; married in 1843.","200034"],
  ["jenny","Jenny von Westphalen Marx","person","reform","1814–1881","Writer & supporter","Born an aristocrat; endured poverty and exile for the socialist cause.","200093"],
  ["burns","Mary Burns","person","reform","1821–1863","Activist","Introduced Engels to Manchester.","200081"],
  ["gibson","TM Gibson","person","reform","1803–1889","Supporter","Anti-slavery.","200007"],
  ["owen","Robert Owen","person","reform","1771–1858","—","Charitable work, status and local power.","200057"],
  ["watkin","Absalom Watkin","person","reform","1787–1861","Parliamentary reformer","Member of the Little Circle; supported parliamentary reform; financial backer of the Manchester Guardian.","200103","Duplicated as 200015 with the same dates."],
  ["brotherton","Joseph Brotherton","person","reform","1783–1857","Preacher & MP","Member of the Little Circle; vegetarian; financial backer of the Manchester Guardian. Buried at Weaste Cemetery.","200107","Duplicated as 200037 with the same dates."],
  ["martha","Martha Brotherton","person","arts","1782–1861","Writer & reformer","Author of Vegetable Cookery (1812), the first known vegetarian cookbook; active in the Bible Christian Church.","200087","Also appears as 200038 'Mary Brotherton' with identical dates — almost certainly the same person."],
  ["helenb","Helen Brotherton","person","reform","1812–1898","—","Daughter of Martha and Joseph Brotherton; vice-president of the Vegetarian Society; dedicated to charity and reform in Salford.","200088"],

  // ---------- civic & institutions ----------
  ["waterhouse","Alfred Waterhouse","person","civic","1830–1905","Architect","Designed Manchester Town Hall.","200045"],
  ["potts","Edward Potts","person","civic","1839–1909","Architect","Designed and built multiple mills, especially in Oldham.","200072","Relationships field reads '2,3,7' — an unresolved cross-reference."],
  ["lane","Richard Lane","person","civic","1795–1880","Architect","Redesigned the esplanade outside the Royal Infirmary; campaigning and design for outdoor public spaces.","200052","Role field contains a description, not a role."],
  ["arnout","J Arnout","person","civic","dates unknown","Lithographer","Lithograph of the Royal Infirmary, 1857.","200051","Role field contains a description, not a role."],
  ["heron","Joseph Heron","person","civic","1809–1889","Town Clerk","Led on building the Town Hall to Waterhouse's design.","200060"],
  ["fraser","Bishop James Fraser","person","civic","1818–1885","Bishop","Statue in Albert Square.","200044"],
  ["dalton","John Dalton","person","civic","1766–1844","Scientist","Statue at the Royal Infirmary.","200053"],
  ["watt","James Watt","person","civic","1736–1819","Engineer","Statue at the Royal Infirmary.","200054"],
  ["wellington","Duke of Wellington","person","civic","1769–1852","—","Statue in Albert Square.","200055"],
  ["peel","Robert Peel","person","civic","1788–1850","Police","Married in 1820; daughter of General Sir John Floyd.","200036"],
  ["caminada","Jerome Caminada","person","civic","1844–1914","Police officer","Dubbed Manchester's Sherlock Holmes. Led a police raid on a cross-dressing ball in Hulme.","200070"],
  ["mcaminada","Mary Ellen Caminada","person","civic","dates not known","Homemaker & supporter","Wife of Jerome Caminada; raised the family during his public career. Married 1871.","200095"],
  ["stokes","Harry Stokes","person","civic","c.1799–1859","Constable","Assigned female at birth but lived as a man. Owned a bar on Quay Street.","200061"],
  ["henshaw","Thomas Henshaw","person","civic","1731–1810","Founder","Blind Asylum. Disability.","200026","Institution name is embedded in the Name field."],
  ["birley","Hugh Hornby Birley","person","civic","1778–1845","Founder","Deaf institute. A leading role in the Peterloo Massacre.","200028","Role field records the institution, not a role."],
  ["pendlebury","John Pendlebury","person","civic","dates unknown","—","—","200027"],
  ["cooke","Alice Cooke","person","civic","1867–1940","Academic","Catalogued the Enriqueta collection; studied at Manchester University.","200073"],
  ["foster","Agnes Foster","person","civic","dates unknown","Salvationist","Co-founder of the Jamaican Salvation Army but lived in Manchester; became a soldier in the Eccles corps.","200067","Spelled 'Jamacian'."],

  // ---------- arts & performance ----------
  ["gaskell","Elizabeth Gaskell","person","arts","1810–1865","Writer & philanthropist","Wrote novels about industrial Manchester; involved in charities. Liberal, Unitarian, 1830s–1860s.","200082"],
  ["bronte","Charlotte Brontë","person","arts","1816–1855","Writer","Wrote Jane Eyre in Manchester.","200064"],
  ["horniman","Annie Horniman","person","arts","1860–1937","Theatre patron","Founded and managed the Gaiety Theatre. Close friends with W.B. Yeats.","200074"],
  ["fanque","Pablo Fanque","person","arts","1810–1871","Equestrian & circus proprietor","The first recorded non-white British circus owner. Inspired a song by the Beatles.","200063","Note spells it 'Beetles'."],
  ["marlaw","Susannah Marlaw","person","arts","c.1815–1848","Performer","Wife of Pablo Fanque; performed in his circus and died when a circus stand collapsed in 1848.","200098"],
  ["lala","Miss Lala","person","arts","1858–unknown","Acrobat","Mixed-race performer in a travelling circus; frequently performed at the Gaiety Theatre.","200071"],
  ["rose","Robert Rose","person","arts","dates unknown","Poet","Born in the West Indies and lived in Salford. Vice-chair of the 'Poets Corner'.","200065"],
  ["corkling","Mary Corkling","person","arts","1850–1928","Artist & food campaigner","—","200022"],
  ["armitt","Mary Louisa Armitt","person","arts","1851–1911","Writer & polymath","Born in Salford; contributed to music criticism and ornithology and founded the Armitt Library in Ambleside.","200089"],
  ["delaney","Shelagh Delaney","person","arts","1938–2011","Playwright","From Broughton, Salford; wrote A Taste of Honey (1958).","200090","Twentieth century; the People sheet carries no scope flag."],
  ["wharton","Arthur Wharton","person","arts","1865–1930","Footballer","The first black professional footballer.","200075","Gender recorded as F; the record and its source describe a man."],
  ["peters","James Peters","person","arts","1879–1954","Rugby player","The first black man to play rugby union for England; remained the only one until 1988.","200080"],
  ["isitt","Kate Isitt","person","arts","1910s–1940s active","Journalist","Journalist for the Guardian, originally from New Zealand.","—","No ID and no dates; active well after the Victorian period."],

  // ---------- organisations ----------
  ["litphil","Manchester Literary & Philosophical Society","org","nat","1781","Learned society","Lectures and networks linking science, civic culture and industry.","ORG-REL-001"],
  ["mechinst","Manchester Mechanics' Institute","org","nat","1824","Adult education","Self-education and lectures; a bridge between artisan learning and formal institutions. Princess Street.","ORG-REL-002"],
  ["mspnh","Manchester Society for the Promotion of Natural History","org","nat","1821","Society & museum precursor","Formed to display John Leigh Philips's and other private collections; foundational to Manchester Museum.","ORG-NH-001"],
  ["mnhs","Manchester Natural History Society","org","nat","19th century","Natural-history society","Associated with the Peter Street museum; collections later transferred to Owens College.","ORG-NH-002","Formal naming and legal continuity with the 1821 society still to be clarified."],
  ["prestwichbs","Prestwich Botanical Society","org","nat","1820","Working-class botanical society","Pub-based specimen identification, oral teaching and pooled purchase of books and herbaria.","ORG-NH-003"],
  ["ulbs","United Lancashire botanical societies","org","nat","by 1830","Federated rotating network","Regional meetings linking botanical groups around north Manchester and Lancashire.","ORG-NH-004","Whether this had a formal name, minutes or membership list is unresolved."],
  ["mfns","Manchester Field-Naturalists' Society","org","nat","1860","Field naturalists' society","Organised excursions and adult natural-history learning; marks the institutionalisation of field science.","ORG-NH-005"],
  ["mms","Manchester Microscopical Society","org","nat","1858; refounded 1880","Microscopical society","Connected specimen study, instrument use, artisan participation and professional science.","ORG-NH-006","The 1858 and 1880 bodies may not be continuous."],
  ["owensmm","Owens College & Manchester Museum","org","nat","1851; museum later","College and museum","Absorbed and institutionalised collections assembled by local societies and private collectors.","ORG-NH-007"],
  ["mes","Manchester Entomological Society","org","nat","1902","Entomological society","A post-Victorian continuation of Manchester amateur entomology and museum contribution.","ORG-NH-008","Flagged post-Victorian in the workbook."],
  ["mcs","Manchester Cryptogamic Society","org","nat","19th century","Specialist botanical society","Potential link between moss, liverwort, fern and fungus specialists and the herbarium.","ORG-NH-009","Foundation date and formal name unconfirmed."],
  ["msb","Manchester Society of Botanists","org","nat","early 19th century","Informal working-class network","A loose grouping with no regular meeting place, funds, books or rules, united by an interest in plants.","ORG-NH-010","Informal: recorded so it is not mistaken for a formal body."],
  ["bbes","Bury Botanical & Entomological Society","org","nat","by 1830","Botanical & entomological society","A potential connection between botany and entomology in the wider artisan network.","ORG-NH-011","Date, membership and relationship to Prestwich unconfirmed."],
  ["guardian","Manchester Guardian","org","press","1821","Newspaper","Founded by John Edward Taylor and financed by a circle of Manchester merchants and reformers.","—"],
  ["littlecircle","The Little Circle","org","press","1810s–1820s","Reform discussion group","Met at John Potter's house; its members contributed to the founding of the Manchester Guardian.","—"],
  ["philipswood","Philips, Wood & Co","org","trade","early 19th century","Hat-making firm","Strong links to enslaved labour in Brazil.","—"],
  ["shuttleworthtaylor","Shuttleworth, Taylor & Co","org","trade","early 19th century","Cotton firm","Imported cotton produced by enslaved people from the Sea Islands region of the United States.","—"],
  ["arttreasures","Art Treasures Exhibition","org","arts","1857","Exhibition","Held at Old Trafford; the collection later dispersed to Manchester Art Gallery and the Whitworth.","—"],
  ["mnsws","Manchester National Society for Women's Suffrage","org","suff","1867","Suffrage society","One of the first formal suffrage organisations in the UK; published the Women's Suffrage Journal.","—"],
  ["nesws","North of England Society for Women's Suffrage","org","suff","1890s","Suffrage society","Focused on women's labour rights.","—"],
  ["mswtc","Manchester & Salford Women's Trades Council","org","suff","1895","Labour organisation","Encouraged women's participation in trade unions; later intersected with suffrage.","—"],
  ["wspu","Women's Social & Political Union","org","suff","1903","Militant suffrage organisation","—","—"],
  ["ilp","Independent Labour Party","org","suff","1893","Political party","Socialism and trade unionism.","—"],
  ["mfrs","Manchester Female Reform Society","org","suff","1819","Reform society","Mary Fildes was president; the society's contingent marched at Peterloo.","—"],
  ["schoolmistresses","Manchester Schoolmistresses Association","org","suff","1865","Professional association","Supported women teachers and advocated for gender equity in education.","—"],
  ["lea","Ladies' Educational Association","org","suff","1865","Education body","Pushed for women's access to higher education; a precursor to university inclusion.","—"],
  ["abolitionsoc","Society for Effecting the Abolition of Slavery","org","reform","1787","Abolition society","—","—"],
  ["unionemanc","Union and Emancipation Society","org","reform","1863","Anti-slavery society","Campaigned against slavery and for working-class rights during the US Civil War.","—"],
  ["vegsoc","Vegetarian Society","org","reform","1847","Campaigning society","Founded in Salford.","—"],
  ["biblechristian","Bible Christian Church","org","reform","1809","Church","Promoted vegetarianism, temperance and social reform; a significant Salford presence.","—"],
  ["corporation","Manchester Corporation","org","civic","1838","Municipal government","Established under the Municipal Corporations Act; the start of modern local government.","—"],
  ["statsoc","Manchester Statistical Society","org","civic","1833","Research society","One of the world's oldest statistical societies; supported reform with evidence.","—"],
  ["athenaeum","Manchester Athenaeum","org","civic","1837","Cultural & educational body","A venue for literary, scientific and political debate among gentlemen merchants.","—"],
  ["guardianscm","Chorlton-on-Medlock Board of Guardians","org","civic","c.1834","Poor Law governance","Managed workhouses and relief.","—"],
  ["crossstreet","Cross Street Chapel","org","reform","rebuilt 1869","Unitarian chapel","A Unitarian hub advocating women's education, abolition and suffrage.","—"],

  // ---------- places ----------
  ["kersal","Kersal Moor","place","nat","1820s onward","Collecting landscape","Site of Buxton and Horsefield's meeting and of the Manchester moth discovery. Salford.","PL-NH-001"],
  ["mereclough","Mere Clough","place","nat","19th century","Clough / field site","An important botanical field site associated with John Horsefield and local rare plants. Prestwich.","PL-NH-002"],
  ["agecroft","Agecroft & the Irwell Valley","place","nat","19th century","River valley","A collecting and walking landscape used to remember artisan naturalists and local geological change.","PL-NH-003"],
  ["besses","Besses o' th' Barn / Whitefield","place","nat","early–mid 19th c.","Home & working landscape","Horsefield's home and weaving base, close to the Prestwich botanical network. Bury.","PL-NH-004"],
  ["goldenlion","Golden Lion","place","nat","19th century","Pub / meeting place","Remembered by Grindon as a site of vigorous botanical discussion.","PL-NH-005","Which Golden Lion, and when meetings occurred, is unresolved."],
  ["prestwich","Prestwich","place","nat","19th century","Township & network centre","The institutional and landscape centre of working-class botanical organisation.","PL-NH-006"],
  ["chatmoss","Chat Moss","place","nat","19th century","Mossland","A major mossland, both a natural-history site and a landscape transformed by infrastructure and agriculture.","PL-NH-007"],
  ["carringtonmoss","Carrington Moss","place","nat","19th century","Mossland","One of the extensive mosses identified by Grindon around Manchester. Trafford.","PL-NH-008"],
  ["ashtonmoss","Ashton Moss","place","nat","19th century","Mossland","Former mossland increasingly brought under cultivation during the Victorian period. Tameside.","PL-NH-009"],
  ["cotterill","Cotterill Clough","place","nat","19th century","Collecting site","A celebrated collecting place for unusual plants within the naturalists' excursion geography.","PL-NH-012"],
  ["peterst","Peter Street Natural History Museum","place","nat","opened 1835","Museum building","The first major public home of the Natural History Society's collections.","PL-NH-013"],
  ["peelpark","Peel Park Museum","place","nat","mid-19th century","Museum","A neighbouring municipal museum referenced in Grindon's regional writing. Salford.","PL-NH-014"],
  ["manmuseum","Manchester Museum, Oxford Road","place","nat","public opening 1888","Museum / university","The institutional destination for society, private and artisan natural-history collections.","PL-NH-015"],
  ["herbarium","Manchester Museum Herbarium","place","nat","19th–20th century","Collection space","Destination for major personal herbaria and smaller collections, including those of incompletely identified women collectors.","PL-NH-016"],
  ["pomona","Pomona Gardens","place","arts","1845 onward","Commercial garden","Opened as Strawberry Gardens; connects horticulture, leisure and urban development.","PL-NH-017"],
  ["chorltonmedlock","Chorlton-on-Medlock","place","nat","19th century","Residential & educational district","Grindon's home area and the location of medical, educational and museum institutions.","PL-NH-018"],
  ["shudehill","Shudehill workshop","place","nat","early 19th century","Workplace & informal science site","An example of natural history practised alongside manual work rather than in a formal institution.","PL-NH-019"],
  ["rsm","Manchester Royal School of Medicine","place","nat","19th century","Educational institution","Grindon lectured in botany here from 1852 until its absorption into Owens College.","PL-NH-021"],
  ["irwell","River Irwell","place","nat","19th century","River system","Connects industrial pollution, urban growth, river valleys and naturalists' observations.","PL-NH-022"],
  ["townhall","Manchester Town Hall","place","civic","1877","Civic building","Used for public lectures, suffrage meetings and civic ceremonies.","—"],
  ["freetradehall","Free Trade Hall","place","suff","1853","Public hall","Hosted major speeches including suffrage and labour activism.","—"],
  ["portico","Portico Library","place","arts","1806","Library","A space where women's writing and lectures took place.","—"],
  ["chethams","Chetham's Library","place","arts","1653","Library","A hub for radical and literary activity that supported women's access.","—"],
  ["plymouthgrove","84 Plymouth Grove","place","arts","1850","House","A salon space for writers, social reformers and women thinkers.","—"],
  ["stpeters","St Peter's Field","place","suff","1819","Public ground","Site of the Peterloo Massacre, now St Peter's Square.","—"],
  ["gaiety","Gaiety Theatre","place","arts","19th century","Theatre","Founded and managed by Annie Horniman.","—"],
  ["rylandslib","John Rylands Library","place","arts","1899","Library","Funded by Enriqueta Rylands in memory of her husband; a rare example of female-led civic philanthropy.","—"],
  ["salfordlads","Salford Lads Club","place","arts","1903","Youth club","Founded by the Groves brothers of Groves and Whitnall Breweries.","—"],
  ["mri","Manchester Royal Infirmary","place","civic","1752","Hospital","Its esplanade carried statues of Dalton, Watt, Whitworth and Fairbairn.","—"],
  ["ancoats","Ancoats","place","trade","late 18th c. onward","Mill district","Mills on Oxford Road and the River Medlock.","—"],
  ["pankhurstcentre","62 Nelson Street","place","suff","1840s house","House","Home of Emmeline Pankhurst; the birthplace of the suffragette movement.","—"],
  ["weaste","Weaste Cemetery","place","reform","1857","Cemetery","Final resting place of Joseph and Martha Brotherton.","—"],
  ["athenaeumbld","Athenaeum, Princess Street","place","civic","1837–39","Building","Venue for literary, scientific and political debate.","—"]
];

/* [source, target, relation, evidence, note] */
const RAW_EDGES = [
  // --- Relationships sheet, REL-001 to REL-018 ---
  ["grindon","rgrindon","spouse & intellectual partner","documented","REL-001. Rosa's work links natural history to women's literary organisation."],
  ["grindon","mfns","co-founder","documented","REL-002, 1860. Grindon helped found the society and organised its excursions."],
  ["jsidebotham","mfns","co-founder","documented","REL-003, 1860. Identified as Grindon's co-founder in Manchester natural-history accounts."],
  ["horsefield","prestwichbs","founder & president","documented","REL-004, 1820–1854. Founded the society and presided for more than thirty years."],
  ["buxton","horsefield","introduced to the network by","documented","REL-005, 1826. A chance meeting on Kersal Moor connected Buxton to organised artisan botany."],
  ["buxton","nowell","publication collaborator","documented","REL-006, 1840s. The herbarium guide records a fasciculus of British mosses under both names."],
  ["cribb","rwood","passed specimens; credit disputed","verify","REL-007, 1829–30. The moth moved through a collector network and was named for Wood rather than Cribb."],
  ["rwood","curtis","sent specimen for identification","verify","REL-008, c.1829–30. Curtis described and named the moth, apparently from a specimen attributed to Wood."],
  ["jlphilips","mspnh","collection became the foundation for","documented","REL-009, 1821. The society formed to display Philips's and other private collections."],
  ["mnhs","owensmm","collections transferred to","documented","REL-010. Society collections became part of the university museum."],
  ["becker","herbarium","specimens retained by","documented","REL-011, 1864 onward. Her award-winning competition specimens survive in the botanical collection."],
  ["grindon","herbarium","herbarium transferred to","documented","REL-012, 1910. One of the museum's three major personal herbaria."],
  ["melvill","herbarium","herbarium transferred to","documented","REL-013, 1904. One of the museum's three major personal herbaria."],
  ["bailey","herbarium","herbarium transferred to","documented","REL-014, 1917. One of the museum's three major personal herbaria."],
  ["becker","mnsws","cross-theme trajectory","interpretive","REL-015. Her botanical work and the constraints on women's scientific participation preceded her suffrage leadership. The workbook asks the workshop to test this causality rather than assume it."],
  ["horsefield","goldenlion","met, debated & exchanged specimens","verify","REL-016. Pubs acted as knowledge spaces, libraries and meeting venues. Venue, dates and attendees still to be identified."],
  ["buxton","goldenlion","met, debated & exchanged specimens","verify","REL-016. Pubs acted as knowledge spaces, libraries and meeting venues."],
  ["jlphilips","mspnh","textile wealth financed","interpretive","REL-018. Philips and Sidebotham show how industrial wealth could be converted into scientific collections and civic institutions."],
  ["jsidebotham","manmuseum","textile wealth financed","interpretive","REL-018. Track capital, labour, colonial materials and institutional credit explicitly."],

  // --- People sheet relationship columns ---
  ["hobson","horsefield","fellow artisan botanist","documented","Hobson's Relationships field names Horsefield and the Manchester artisan botanists."],
  ["jsidebotham","grindon","society colleague","documented","Sidebotham's Relationships field names Grindon and the Field-Naturalists' Society."],
  ["carrington","pearson","herbarium network","documented","Carrington's Relationships field names the Manchester herbarium network and W.H. Pearson."],
  ["thsidebotham","jsidebotham","family scientific network","verify","Recorded as a potential member of the wider Sidebotham network; identity and relationship to confirm."],
  ["buxton","nowell","fellow bryologist","documented","Nowell's Relationships field names Richard Buxton."],
  ["horsefield","buxton","fellow botanist","documented","Horsefield's Relationships field names Richard Buxton."],
  ["sgibson","ulbs","Lancashire artisan botanists","verify","Gibson's Relationships field names the Lancashire artisan botanists generically."],
  ["bailey","herbarium","museum herbarium network","documented","Bailey's Relationships field names the Manchester Museum herbarium network."],
  ["melvill","herbarium","museum herbarium network","documented","Melvill's Relationships field names the Manchester Museum herbarium network."],
  ["hopkins","herbarium","collection held by","verify","Recorded in the Manchester herbarium collection; the collector is incompletely identified."],
  ["jaffrey","herbarium","collection held by","verify","Darjeeling ferns documented in the herbarium guide; collector and intermediaries unidentified."],
  ["crowther","ulbs","early participant","verify","An early participant in the rotating Lancashire botanical meetings."],
  ["crowe","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["warburton","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["hulme","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["eclough","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["hnewton","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["bleackley","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["jshaw","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["darbyshire","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["bentley","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["devonport","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["jturner","ulbs","meeting participant","verify","Named by Grindon among botanists attending regional gatherings."],
  ["horsefield","ulbs","president","documented","1830. Became president of the wider regional botanical meetings. Whether 'president' applied to a formal organisation is unresolved."],

  // --- Organisations sheet, connected people ---
  ["grindon","litphil","connected member","verify","Listed among the society's natural-history connections; precise memberships still to be added."],
  ["horsefield","mechinst","connected member","verify","Listed under the Mechanics' Institute; attendance and lecture evidence still to be found."],
  ["grindon","mechinst","connected member","verify","Listed under the Mechanics' Institute; attendance and lecture evidence still to be found."],
  ["horsefield","prestwichbs","founder","documented","Pub-based specimen identification, oral teaching and pooled purchase of books and herbaria."],
  ["buxton","prestwichbs","member","documented","Named among the society's connected people."],
  ["jsidebotham","mms","connected member","documented","Named among the Microscopical Society's connected people."],
  ["carrington","mms","connected member","documented","Named among the Microscopical Society's connected people."],
  ["brittain","mms","founder","documented","1858. Named among the founders of the first Microscopical Society."],
  ["cash","mcs","connected member","verify","Named in the Cryptogamic Society entry; the society itself needs confirming."],
  ["carrington","mcs","connected member","verify","Named in the Cryptogamic Society entry; the society itself needs confirming."],
  ["horsefield","msb","member of informal network","verify","A loose grouping with no meeting place, funds, books or rules."],
  ["horsefield","bbes","regional naturalist","verify","Named alongside regional naturalists; date and membership unconfirmed."],
  ["mspnh","mnhs","related / successor body","verify","Formal naming, legal continuity and dates relative to the 1821 society still to be clarified."],
  ["mfns","manmuseum","excursion & collection link","documented","Marks the increasing institutionalisation of field science."],
  ["owensmm","manmuseum","institutional home","documented","The museum sits within the Owens College complex on Oxford Road."],

  // --- Places sheet, connected people ---
  ["buxton","kersal","collected at","documented","Site of the Buxton and Horsefield meeting and the Manchester moth discovery."],
  ["horsefield","kersal","collected at","documented","Site of the Buxton and Horsefield meeting."],
  ["cribb","kersal","found the Manchester moth at","documented","1829. Credited with finding the moth here; the naming became a dispute over credit."],
  ["rwood","kersal","collecting network","verify","Named among the Kersal Moor collectors."],
  ["horsefield","mereclough","collected at","documented","An important botanical field site associated with Horsefield and local rare plants."],
  ["grindon","mereclough","collected at","documented","Named among the site's connected people."],
  ["grindon","agecroft","walked & documented","documented","A collecting and walking landscape used to remember artisan naturalists."],
  ["horsefield","besses","lived & worked at","documented","Horsefield's home and weaving base."],
  ["bleackley","besses","local network","verify","Named among the connected people for Besses o' th' Barn."],
  ["horsefield","prestwich","network centre","documented","The institutional and landscape centre of working-class botanical organisation."],
  ["buxton","prestwich","network centre","documented","Named among Prestwich's connected people."],
  ["hulme","prestwich","local botanist","documented","Named among Prestwich's connected people."],
  ["grindon","chatmoss","collected at","documented","Named among the mossland's connected field naturalists."],
  ["grindon","carringtonmoss","collected at","documented","One of the extensive mosses identified by Grindon around Manchester."],
  ["eclough","ashtonmoss","local naturalist","interpretive","Recorded generically as 'Ashton naturalists'; Clough is the workbook's Ashton-under-Lyne botanist."],
  ["hnewton","ashtonmoss","local naturalist","interpretive","Recorded generically as 'Ashton naturalists'; Newton is an Ashton-under-Lyne botanist."],
  ["grindon","cotterill","excursion site","documented","A celebrated collecting place within the naturalists' excursion geography."],
  ["jlphilips","peterst","collection displayed at","documented","The first major public home of the Natural History Society's collections."],
  ["wcwilliamson","peterst","first curator","documented","Recorded as first curator of the Peter Street museum, 1835."],
  ["wcwilliamson","owensmm","professor of natural history","documented","Professor of Natural History at Owens College."],
  ["mnhs","peterst","museum opened at","documented","1835. The Natural History Society museum opened on Peter Street."],
  ["grindon","peelpark","regional museum context","verify","A neighbouring municipal museum referenced in Grindon's regional writing."],
  ["grindon","manmuseum","collection destination","documented","Named among the museum's connected collectors."],
  ["jsidebotham","manmuseum","collection destination","documented","Lepidoptera and wider natural-history collections entered the museum."],
  ["bailey","manmuseum","collection destination","documented","Named among the museum's connected collectors."],
  ["melvill","manmuseum","collection destination","documented","Named among the museum's connected collectors."],
  ["becker","manmuseum","collection destination","documented","Named among the museum's connected collectors."],
  ["carrington","herbarium","collection destination","documented","Hepaticae Britannicae exsiccatae and herbarium material."],
  ["sgibson","herbarium","collection destination","documented","British ferns, algae and allied plants."],
  ["nowell","herbarium","collection destination","documented","Fasciculus of British Mosses with Richard Buxton."],
  ["buxton","herbarium","collection destination","documented","Moss collections with John Nowell."],
  ["hobson","herbarium","collection destination","documented","British mosses and hepatics; Musci Britannici material."],
  ["beardsley","pomona","opened","documented","1845. Opened as Strawberry Gardens, later Pomona Gardens."],
  ["grindon","chorltonmedlock","lived at","documented","Grindon's home area; he wrote excursions for the whole of Greater Manchester."],
  ["crozier","shudehill","worked at","documented","Remembered by Grindon as practising natural history alongside manual work."],
  ["grindon","rsm","lectured at","documented","Lectured in botany here from 1852 until absorption into Owens College."],
  ["grindon","irwell","observed & documented","interpretive","Connects industrial pollution, urban growth, river valleys and naturalists' observations."],
  ["horsefield","goldenlion","botanical discussion at","verify","Remembered by Grindon as a site of vigorous botanical discussion."],

  // --- Timeline ---
  ["crowther","ulbs","early rotating meetings","verify","TL-NH-001, c.1770s–1790s. Early artisan botanical societies and rotating meetings develop."],
  ["horsefield","msb","loose botanists' network","verify","TL-NH-002, 1808. Horsefield participates in a loose Manchester botanists' network."],
  ["becker","mnsws","founder","documented","TL-BASE-006, 1867. Founder of the women's suffrage society; edited the Women's Suffrage Journal."],

  // --- Press: the Little Circle and the Guardian ---
  ["jetaylor","guardian","founded","documented","Founded the Manchester Guardian."],
  ["jetaylor2","guardian","co-owner then sole owner","documented","Co-owner in 1852, sole owner in 1856; expanded the paper's reach."],
  ["jetaylor","jetaylor2","father & son","documented","Son of John Edward Taylor."],
  ["rscott","guardian","investor & proprietor","documented","Invested in the Guardian and became proprietor after Taylor's death."],
  ["rscott","jetaylor","brother-in-law","documented","Brother-in-law to John Edward Taylor."],
  ["jetaylor","sophiataylor","spouse","documented","Husband of Sophia Russell Taylor, née Scott."],
  ["cowdroy","littlecircle","member","documented","Member of the Little Circle; contributed to the founding of the Manchester Guardian."],
  ["prentice","littlecircle","member","documented","Member of the Little Circle; advocated radical reforms; financial backer."],
  ["rpotter","littlecircle","member","documented","Member of the Little Circle; early supporter and financier."],
  ["tpotter","littlecircle","member","documented","Member of the Little Circle; early supporter and financier."],
  ["watkin","littlecircle","member","documented","Member of the Little Circle; supported parliamentary reform."],
  ["brotherton","littlecircle","member","documented","Member of the Little Circle; supported social reforms."],
  ["shuttleworth","littlecircle","member","documented","Named among the Little Circle's Guardian backers."],
  ["jpotter","littlecircle","host","documented","Host of the Little Circle meetings."],
  ["littlecircle","guardian","founded & financed","documented","The circle's members contributed to founding and financing the paper."],
  ["gphilips","guardian","backer","documented","The Guardian backer most deeply linked with slavery."],
  ["baxter","guardian","backer","verify","Named in the research on the paper's commercial backers."],
  ["duckworth","guardian","backer","verify","Recorded in 1826 alongside Taylor and Wood on the condition of the enslaved population."],
  ["rphilips","guardian","backer","verify","Named in the research on the paper's commercial backers."],
  ["pullein","guardian","backer","verify","Named in the research on the paper's commercial backers."],
  ["sanderson","guardian","backer","verify","Named in the research on the paper's commercial backers."],
  ["gwwood","guardian","backer","verify","Named in the research on the paper's commercial backers."],
  ["tjohnson","guardian","named in the loan agreement","documented","The original Manchester Guardian loan agreement names him as a merchant."],
  ["twilkins","guardian","named in the loan agreement","documented","The loan agreement names him as a merchant; a secondary source lists him as a cotton merchant."],
  ["jpotter","tpotter","father & son","documented","Father to Thomas and Richard Potter."],
  ["jpotter","rpotter","father & son","documented","Father to Thomas and Richard Potter."],
  ["tpotter","rpotter","brothers","documented","The brother of Richard Potter; in partnership with him in cotton and textiles."],
  ["gphilips","rphilips","cousins","documented","Robert Philips is recorded as the cousin of Sir George Philips."],
  ["duckworth","rphilips","son-in-law","documented","A Unitarian attorney and son-in-law of Robert Philips."],
  ["gwwood","rphilips","family relation","verify","Recorded as a relative of the Philips family."],
  ["gphilips","philipswood","partner","documented","Partnerships in Philips, Wood & Co, with strong links to enslaved labour in Brazil."],
  ["gwwood","philipswood","partner","documented","Partner in Philips, Wood & Co."],
  ["rphilips","philipswood","partner","documented","Partnerships spanned Philips, Wood & Co."],
  ["shuttleworth","shuttleworthtaylor","co-founder","documented","Co-founded the firm, which imported cotton produced by enslaved people."],
  ["jetaylor","shuttleworthtaylor","partner","documented","Partnered in Shuttleworth, Taylor & Co."],
  ["gwwood","shuttleworthtaylor","partner","documented","Partner in Shuttleworth, Taylor & Co."],
  ["rphilips","shuttleworthtaylor","partner","documented","Partnerships spanned Shuttleworth, Taylor & Co."],
  ["tpotter","corporation","first mayor","documented","First mayor of Manchester, serving from 1838 to 1840."],
  ["mosley","corporation","sold manorial rights to","documented","Sold the rights of lord of the manor of Manchester to the Corporation in 1846."],

  // --- Suffrage & women's rights ---
  ["roper","gorebooth","partner","documented","Partner of Esther Roper; campaigned for women's and workers' rights."],
  ["roper","mnsws","secretary","documented","Appointed secretary in 1893; focused on recruiting working-class women."],
  ["roper","nesws","organiser","documented","North of England Society for Women's Suffrage, 1890s to early 1900s."],
  ["gorebooth","nesws","organiser","documented","Named under the North of England Society in her People row."],
  ["gorebooth","mswtc","co-founder","documented","1895. Formed the council with Sarah Dickenson and Frances Ashwell."],
  ["dickenson","mswtc","co-founder","documented","1895. Named in the events sheet as a founder."],
  ["quaile","mswtc","secretary","documented","Secretary of the Manchester Women's Trade Union Council."],
  ["becker","freetradehall","spoke at","documented","Named among the hall's connected women."],
  ["fildes","freetradehall","connected","documented","Named among the hall's connected women."],
  ["gorebooth","freetradehall","connected","documented","Named among the hall's connected women."],
  ["pochin","freetradehall","spoke at","documented","1868. Delivered a speech at the Free Trade Hall; her husband, then Mayor of Salford, chaired the meeting."],
  ["brightmclaren","mnsws","spoke at first public meeting","documented","14 April 1868, Free Trade Hall."],
  ["robertson","mnsws","spoke at first public meeting","documented","14 April 1868, Free Trade Hall."],
  ["wolstenholme","mnsws","founding participant","documented","January 1867. Present at the society's formation."],
  ["rpankhurst","mnsws","founding participant","documented","January 1867. Present at the society's formation."],
  ["ubright","mnsws","founding participant","documented","January 1867. Present at the society's formation."],
  ["jacobbright","mnsws","founding participant","documented","January 1867. Present at the society's formation."],
  ["butler","mnsws","executive committee","documented","30 October 1868. Joined the new executive committee."],
  ["wolstenholme","schoolmistresses","founder","documented","2 December 1865. Inaugurated the association."],
  ["aclough","schoolmistresses","honorary member","documented","2 December 1865. Honorary member at the inauguration."],
  ["davies","schoolmistresses","addressed","documented","October 1866. Advocated women's access to university-level education."],
  ["kenney","wspu","senior leadership","documented","The only working-class woman in a senior leadership position in the WSPU."],
  ["pankhurst","wspu","founder","documented","Her Nelson Street home is recorded as the birthplace of the suffragette movement."],
  ["pankhurst","pankhurstcentre","lived at","documented","Home of Emmeline Pankhurst."],
  ["pankhurst","guardianscm","Poor Law Guardian","documented","1894. Elected Poor Law Guardian for Chorlton-on-Medlock."],
  ["mitchell","ilp","member","documented","ILP and trade unions; socialist."],
  ["martyn","ilp","speaker","documented","ILP and trade unions; worked alongside Keir Hardie."],
  ["fildes","mfrs","president","documented","Irish-born president of the Manchester Female Reform Society."],
  ["fildes","stpeters","led the female reformers' contingent","documented","16 August 1819. The peaceful protest turned tragic when cavalry charged the crowd."],
  ["birley","stpeters","leading role in the massacre","documented","Recorded as having a leading role in the Peterloo Massacre."],
  ["ashton","townhall","first woman city councillor","documented","1908. Advocated public health initiatives including mother and baby clinics."],
  ["becker","townhall","connected","documented","Named among the Town Hall's connected women."],
  ["becker","portico","connected","documented","Named among the Portico Library's connected women."],
  ["gaskell","portico","connected","documented","Named among the Portico Library's connected women."],
  ["becker","chethams","research access","documented","Named among Chetham's Library's connected women."],
  ["gaskell","chethams","connected","documented","Named among Chetham's Library's connected women."],
  ["becker","lea","women's higher education","interpretive","The association pushed for women's access to higher education in the same decade and city."],
  ["maxwell","mnsws","test case","documented","Chorlton v Lings; one of the first women to vote, illegally."],
  ["rgrindon","becker","women's literary organisation","interpretive","The workbook asks the workshop to connect Rosa to Grindon's household network and Becker's women's literary organisation."],
  ["ubright","jacobbright","spouse","documented","Wife of Jacob Bright."],
  ["mbright","jbright","spouse","documented","Second wife of John Bright; married 1847."],
  ["mbright","jacobbright","sister","verify","Recorded as 'sister to Jacob Bright'; probably sister-in-law. Worth resolving."],

  // --- Reform & abolition ---
  ["clarkson","abolitionsoc","founder member","documented","Society for Effecting the Abolition of Slavery."],
  ["sharp","abolitionsoc","founder member","documented","Anti-slavery, with Wilberforce in London."],
  ["clarkson","cclarkson","spouse","documented","Married in 1796; their only child died before his father."],
  ["cobden","ccobden","spouse","documented","Married in 1840; five surviving children."],
  ["marx","jenny","spouse","documented","Childhood sweetheart; married in 1843."],
  ["engels","burns","long-term partner","documented","Long-term relationships with Mary Burns and later her sister Lydia, but did not marry."],
  ["engels","marx","collaborator","interpretive","Both recorded under Socialism in the workbook; the relationship itself is not stated."],
  ["remond","athenaeum","delivered speeches at","documented","Delivered speeches in the Manchester Athenaeum."],
  ["remond","unionemanc","anti-slavery campaigning","interpretive","Both sit in the workbook's anti-slavery cluster; the link is not stated directly."],
  ["gibson","unionemanc","supported Lincoln in the US Civil War","verify","Recorded in the anti-slavery supporters block."],
  ["brotherton","vegsoc","vegetarianism","documented","Recorded under Vegetarianism; the society was founded in Salford in 1847."],
  ["helenb","vegsoc","vice-president","documented","Vice-president of the Vegetarian Society."],
  ["brotherton","martha","spouse","documented","Husband of Martha Harvey."],
  ["martha","biblechristian","active member","documented","Active in the Bible Christian Church and social reform movements."],
  ["brotherton","biblechristian","preacher","documented","Recorded as Preacher, MP; the church promoted vegetarianism and temperance."],
  ["helenb","martha","daughter","documented","Daughter of Martha and Joseph Brotherton."],
  ["helenb","brotherton","daughter","documented","Daughter of Martha and Joseph Brotherton."],
  ["brotherton","weaste","buried at","documented","Final resting place of Joseph and Martha Brotherton."],
  ["martha","weaste","buried at","documented","Final resting place of Joseph and Martha Brotherton."],
  ["gaskell","crossstreet","congregation","documented","Named among Cross Street Chapel's connected women."],
  ["gaskell","plymouthgrove","lived at","documented","Her house was completed at 84 Plymouth Grove in 1850."],

  // --- Industry, civic & arts ---
  ["whitworth","mlwhitworth","spouse","documented","Second wife; married 1871 after Frances Anker's death in 1870."],
  ["rylands","erylands","spouse","documented","Married Enriqueta in 1875, eight months after Martha's death."],
  ["erylands","rylandslib","founded","documented","Founded the John Rylands Library in memory of her husband."],
  ["cooke","erylands","catalogued the collection of","documented","Catalogued the Enriqueta collection."],
  ["rylands","jwilliamson","Manchester Royal Jubilee Exhibition","verify","Both recorded under the Manchester Royal Jubilee Exhibition."],
  ["waterhouse","townhall","architect","documented","The Town Hall was built to Waterhouse's design."],
  ["heron","townhall","Town Clerk; led the building","documented","Town Clerk who led on building the Town Hall in Waterhouse's design."],
  ["lane","mri","redesigned the esplanade","documented","Redesign of the esplanade outside the Royal Infirmary."],
  ["arnout","mri","lithograph of","documented","Lithograph of the Royal Infirmary, 1857."],
  ["whitworth","mri","statue at","documented","Statues at the Royal Infirmary."],
  ["dalton","mri","statue at","documented","Statues at the Royal Infirmary."],
  ["watt","mri","statue at","documented","Statues at the Royal Infirmary."],
  ["wfairbairn","mri","statue at","documented","Statues at the Royal Infirmary."],
  ["murray","ancoats","mill owner","documented","Factory owners, Ancoats."],
  ["mcconnel","ancoats","mill owner","documented","Factory owners, Ancoats."],
  ["kennedy","ancoats","mill owner","documented","Mill owners, Oxford Road and the River Medlock."],
  ["tfairbairn","arttreasures","headed the executive committee","documented","1857. Local industrialist, art collector and patron."],
  ["caminada","mcaminada","spouse","documented","Husband of Mary Ellen Walsh; married 1871."],
  ["jgroves","salfordlads","founder","documented","Salford Lads Club; Groves and Whitnall Breweries."],
  ["wgroves","salfordlads","founder","documented","Salford Lads Club; Groves and Whitnall Breweries."],
  ["jgroves","wgroves","brothers","verify","Both recorded as founders of the same club and brewery."],
  ["fanque","marlaw","spouse","documented","Susannah performed in his circus and died when a stand collapsed in 1848."],
  ["horniman","gaiety","founded & managed","documented","Founded and managed the Gaiety Theatre."],
  ["lala","gaiety","performed at","documented","Frequently performed in the Gaiety Theatre, Manchester."],
  ["swatts","ancoats","warehouse","interpretive","Their warehouse, now the Britannia Hotel, sits in the same commercial fabric."],
  ["sichel","manmuseum","diaries held by","documented","Manchester Museum has his diaries."],
  ["armitt","manmuseum","ornithology & natural history","interpretive","A polymath who contributed to ornithology; her library went to Ambleside, not Manchester."],
  ["sophiataylor","gaskell","Manchester salons","interpretive","Hosted cultural salons; Gaskell moved in Manchester's Unitarian elite. Potential cross-network salon link."]
];

/* Active spans. WB_SPAN marks the ones the workbook's own "Decades active"
   column gives; everything else app.js infers from the lifespan and labels
   as inferred, so the slider never passes off a guess as a record. */
const SPANS = {
  remond:[1850,1869], cooke:[1880,1899], lala:[1870,1889], burns:[1840,1869],
  potts:[1870,1899], rscott:[1820,1889], stokes:[1830,1859], cowdroy:[1820,1839],
  prentice:[1820,1859], jetaylor2:[1850,1909], fanque:[1840,1869], gphilips:[1820,1849],
  tpotter:[1820,1849], wharton:[1880,1909], jetaylor:[1820,1849], shuttleworth:[1820,1869],
  rgrindon:[1860,1889], jpotter:[1820,1839], rpotter:[1820,1849], watkin:[1820,1869],
  rose:[1840,1849], gorebooth:[1890,1919], caminada:[1860,1889], ashton:[1890,1919],
  brotherton:[1820,1859], fildes:[1810,1849], peters:[1900,1909], foster:[1850,1889],
  becker:[1860,1899], mitchell:[1890,1919], martyn:[1890,1899], kenney:[1900,1909],
  maxwell:[1840,1869], roper:[1890,1909], cobden:[1830,1859], horniman:[1880,1909],
  quaile:[1890,1919], bronte:[1840,1849], gaskell:[1830,1869], isitt:[1910,1949],
  grindon:[1850,1899], buxton:[1820,1869], horsefield:[1800,1859], hobson:[1810,1829],
  jsidebotham:[1840,1889], jlphilips:[1780,1819], cribb:[1820,1829], rwood:[1820,1839],
  carrington:[1850,1899], bailey:[1860,1919], melvill:[1860,1909], sgibson:[1830,1849],
  nowell:[1840,1869], crozier:[1800,1839], crowther:[1770,1849], thsidebotham:[1800,1899],
  crowe:[1800,1899], warburton:[1800,1899], hulme:[1800,1899], eclough:[1800,1899],
  hnewton:[1800,1899], bleackley:[1800,1899], jshaw:[1800,1899], darbyshire:[1800,1899],
  bentley:[1800,1899], devonport:[1800,1899], jturner:[1800,1899],
  hopkins:[1879,1881], jaffrey:[1882,1882], armitt:[1851,1911], delaney:[1938,2011],

  litphil:[1781,1910], mechinst:[1824,1910], mspnh:[1821,1850], mnhs:[1830,1888],
  prestwichbs:[1820,1900], ulbs:[1830,1880], mfns:[1860,1910], mms:[1858,1910],
  owensmm:[1851,1910], mes:[1902,1910], mcs:[1850,1900], msb:[1800,1850],
  bbes:[1830,1880], guardian:[1821,1910], littlecircle:[1815,1830],
  philipswood:[1800,1845], shuttleworthtaylor:[1810,1855], arttreasures:[1857,1857],
  mnsws:[1867,1910], nesws:[1890,1910], mswtc:[1895,1910], wspu:[1903,1910],
  ilp:[1893,1910], mfrs:[1819,1835], schoolmistresses:[1865,1885], lea:[1865,1895],
  abolitionsoc:[1787,1840], unionemanc:[1863,1870], vegsoc:[1847,1910],
  biblechristian:[1809,1910], corporation:[1838,1910], statsoc:[1833,1910],
  athenaeum:[1837,1910], guardianscm:[1834,1910], crossstreet:[1800,1910],

  kersal:[1820,1900], mereclough:[1800,1900], agecroft:[1800,1900], besses:[1800,1860],
  goldenlion:[1800,1900], prestwich:[1800,1900], chatmoss:[1800,1900],
  carringtonmoss:[1800,1900], ashtonmoss:[1800,1900], cotterill:[1800,1900],
  peterst:[1835,1888], peelpark:[1850,1900], manmuseum:[1888,1910],
  herbarium:[1860,1910], pomona:[1845,1900], chorltonmedlock:[1800,1910],
  shudehill:[1800,1850], rsm:[1824,1880], irwell:[1800,1910], townhall:[1877,1910],
  freetradehall:[1853,1910], portico:[1806,1910], chethams:[1800,1910],
  plymouthgrove:[1850,1910], stpeters:[1819,1819], gaiety:[1880,1910],
  rylandslib:[1899,1910], salfordlads:[1903,1910], mri:[1800,1910],
  ancoats:[1780,1910], pankhurstcentre:[1840,1910], weaste:[1857,1910],
  athenaeumbld:[1837,1910]
};

/* Spans the workbook states outright, rather than ones derived from a lifespan. */
const WB_SPAN = new Set(["remond","cooke","lala","burns","potts","rscott","stokes",
  "cowdroy","prentice","jetaylor2","fanque","gphilips","tpotter","wharton","jetaylor",
  "shuttleworth","rgrindon","jpotter","rpotter","watkin","rose","gorebooth","caminada",
  "ashton","brotherton","fildes","peters","foster","becker","mitchell","martyn","kenney",
  "maxwell","roper","cobden","horniman","quaile","bronte","gaskell","isitt","grindon",
  "buxton","horsefield","hobson","jsidebotham","jlphilips","cribb","rwood","carrington",
  "bailey","melvill","sgibson","nowell","crozier","crowther","thsidebotham","crowe",
  "warburton","hulme","eclough","hnewton","bleackley","jshaw","darbyshire","bentley",
  "devonport","jturner","hopkins","jaffrey"]);
